# Generated by Django 3.1.12 on 2023-01-08 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('symbol', models.CharField(max_length=10, unique=True)),
                ('total_stocks', models.IntegerField(default=0)),
                ('remaining_stocks', models.IntegerField(default=0)),
                ('average_stock_price', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('trade_type', models.CharField(choices=[('B', 'Buy'), ('S', 'Sell')], max_length=1)),
                ('qty', models.FloatField()),
                ('outstanding_qty', models.FloatField()),
                ('outstanding_models', models.FloatField()),
                ('price', models.FloatField()),
                ('amount', models.FloatField()),
                ('total_exit', models.TextField(default=None, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.company')),
            ],
        ),
        migrations.CreateModel(
            name='StockSplit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('ratio', models.FloatField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.company')),
            ],
        ),
    ]
