# Generated by Django 3.1.12 on 2023-01-08 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trade',
            old_name='outstanding_models',
            new_name='outstanding_amount',
        ),
    ]
