# Generated by Django 3.1.12 on 2023-01-08 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_auto_20230108_0633'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='avg_buy_price',
            field=models.FloatField(default=None, null=True),
        ),
    ]
